[package]
name = "raw-mqtt-stream-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-mqtt-lib = { path = "../raw-mqtt-lib", version = "0.1.0", features = ["pub_stream"] }
clap = "4.4.18"
log = "0.4.20"
tokio = "1.35.1"
env_logger = "0.11.0"
chrono = "0.4.32"
mqttbytes = "0.6.0"

