[package]
name = "raw-mqtt-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
raw-mqtt-lib = { path = "../raw-mqtt-lib", version = "0.1.0"}
clap = "4.4.18"
log = "0.4.20"
tokio = { version = "1.35.1", features = [] }
env_logger = "0.11.0"
mqttbytes = "0.6.0"
